// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrhCgWy2kVYVI7t9kQ9-qYvippBcuztA',
    appId: '1:106112278713:web:3ec309d737c5aace67bb68',
    messagingSenderId: '106112278713',
    projectId: 'authtutorialkoko-b0a9c',
    authDomain: 'authtutorialkoko-b0a9c.firebaseapp.com',
    storageBucket: 'authtutorialkoko-b0a9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3q9b2KoxEUUGTY_lia0rdAhIr9-WQtZs',
    appId: '1:106112278713:android:a2a66a05989f049667bb68',
    messagingSenderId: '106112278713',
    projectId: 'authtutorialkoko-b0a9c',
    storageBucket: 'authtutorialkoko-b0a9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYe7EgG9swhCtRVsCUKXMaQNRrFLkwHb8',
    appId: '1:106112278713:ios:59a0e872a277d58767bb68',
    messagingSenderId: '106112278713',
    projectId: 'authtutorialkoko-b0a9c',
    storageBucket: 'authtutorialkoko-b0a9c.firebasestorage.app',
    iosBundleId: 'com.example.authKoko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYe7EgG9swhCtRVsCUKXMaQNRrFLkwHb8',
    appId: '1:106112278713:ios:59a0e872a277d58767bb68',
    messagingSenderId: '106112278713',
    projectId: 'authtutorialkoko-b0a9c',
    storageBucket: 'authtutorialkoko-b0a9c.firebasestorage.app',
    iosBundleId: 'com.example.authKoko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTrhCgWy2kVYVI7t9kQ9-qYvippBcuztA',
    appId: '1:106112278713:web:7e6db3bb2a4412e267bb68',
    messagingSenderId: '106112278713',
    projectId: 'authtutorialkoko-b0a9c',
    authDomain: 'authtutorialkoko-b0a9c.firebaseapp.com',
    storageBucket: 'authtutorialkoko-b0a9c.firebasestorage.app',
  );

}